name: Contrast Check
on:
  push:
    branches: [ main, styling ]
  pull_request:
    branches: [ main, styling ]

jobs:
  contrast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install pnpm
        run: npm i -g pnpm@10
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Run contrast check
        working-directory: frontend
        run: pnpm contrast
